spring:
  main:
    banner-mode: log
  profiles:
    active: test
mars:
  version: V1.0.0
#配置日志地址
logging:
  file:
    path: ./logs/${spring.profiles.active}
    max-history: 30
    total-size-cap: 3GB
server:
  servlet:
    session:
      cookie:
        http-only: true
